# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Open-source firewall for AI agents"
  homepage "https://rampart.sh"
  version "1.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peg/rampart/releases/download/v1.6.1/rampart_1.6.1_darwin_amd64.tar.gz"
      sha256 "37c4d4ddc1d76f327d7c268e63cd2c552bbc3b8f2501feb890bc6649b5b021d1"

      define_method(:install) do
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peg/rampart/releases/download/v1.6.1/rampart_1.6.1_darwin_arm64.tar.gz"
      sha256 "e505c8f4f17a4de42dcadb0912e479fedc93514307a2d41e38b61ccb583a5194"

      define_method(:install) do
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v1.6.1/rampart_1.6.1_linux_amd64.tar.gz"
      sha256 "48237f46c4792765327100f6b8638fd282700389a808581f3e950289e0cad4a6"
      define_method(:install) do
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v1.6.1/rampart_1.6.1_linux_arm64.tar.gz"
      sha256 "1312e45905f5f47fd297861355d7ed47ec6c7f467f7be1a3c6b2c1e8cbb97a6a"
      define_method(:install) do
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "version"
  end
end
